### ISSUE TITLE
Consultar IE através do CNPJ

### ISSUE THREAD

**Issue by eduardo-mior** [frones/nfe#5]
Notei que o seu pacote possui uma função chamada Consulta que recebe uma struct.
Gostaria de saber para que serve exatamente essa função, se é possível consultar uma IE através do CNPJ.

**Comment by frones** [comment]
Oi, Eduardo. Sim, vc pode consultar uma IE através do CNPJ usando [essa função](https://github.com/frones/nfe/blob/master/cadastro.go#L138). Basicamente vc poderia usar a função assim:

```
	client, err := nfe.NewHTTPClient(arquivo_cert, arquivo_keyfile)
	if err != nil {
		//tratar erro
		return
	}
	ret, _, err := nfe.ConsultaCad("", cnpj, "", codigo_uf_ibge, Producao/Homologacao, client)
	if err != nil {
		//tratar erro
		return
	}
```

O código da UF (IBGE) aqui é importante porque essa lib faz a consulta no webservice da UF de origem do CNPJ pra buscar as informações.

O retorno vai ser do tipo `RetConsCad` e você pode ler o array `InfCad` para buscar a informação que precisa. Atenção que um mesmo CNPJ pode ter vários IEs nessa lista (por exemplo, se IEs anteriores foram canceladas).

**Comment by eduardo-mior** [comment]
@frones incrível, era exatamente isso que eu precisava! Porém fiz exatamente isso e não funcionou, retornou um erro código 999 da sefaz (não sei se é na sefaz que consulta, estou presumindo pois não entendo muito disso) e retornou um XML e uma mensagem de erro genérico, amanhã eu mando mais detalhes.

Existe alguma outra peculiaridade nessa consulta? O CNPJ precisa estar formatado com os . e / ou não? Amanhã eu mando meu código e o retorno do erro.

**Comment by eduardo-mior** [comment]
@frones revisei aqui meu código e estava faltando passar a versão que é "2.00", também testei aquele código ali que vc tinha passado e funcionou também.

**Comment by eduardo-mior** [comment]
Não estou trabalhando mais com isso, então vou fechar a issue por falta de oportunidade e tempo de finalizar os testes.

Novamente parabéns pelo pacote, acho muito interessante a usa ideia e a sua disposição.
